# Generated by Django 4.1.7 on 2023-03-03 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menu_url_menuitem_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='url',
            new_name='path',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='url',
            new_name='path',
        ),
    ]
